#!/bin/sh
#
#   /etc/init.d/perpetualvault
#
# Starts the maidsafe perpetual data Daemon (vault)
#
# chkconfig: 2345 90 10
# description: Perpetual Data Vault Daemon

# processname: perpetualvault

#source /etc/init.d/functions

[ -x /usr/bin/vault ] || exit 1

RETVAL=0
prog="vault"
desc="Perpetual Vault Daemon"

start() {
   echo -n $"Starting $desc ($prog): "
   /usr/bin/vault
   RETVAL=$?
  if  `grep  maidsafe /etc/passwd >/dev/null` ; then
  echo " "	
  else
   	/usr/sbin/adduser --system --shell /bin/false --no-create-home maidsafe
   fi
   if [ ! -e /var/cache/maidsafe/ ]; then
   	mkdir -p /var/cache/maidsafe
	/bin/chown maidsafe /var/cache/maidsafe
   fi

   [ $RETVAL -eq 0 ] #&& touch /var/lock/subsys/$prog
   echo "Vault started OK! "
}

stop() {
   echo -n $"Shutting down $desc ($prog): "
   pkill $prog  > /dev/null
   #rm -f /var/lock/subsys/$prog
   RETVAL=$?
   return $RETVAL
}

case "$1" in
  start)
   start
   ;;
  stop)
   stop
   ;;
  restart)
   stop
   start
   RETVAL=$?
   ;;
  condrestart)
        [ -e /var/lock/subsys/$prog ] && restart
   RETVAL=$?
   ;;
  *)
   echo $"Usage: $0 {start|stop|restart|condrestart}"
   RETVAL=1
   ;;
esac

exit $RETVAL 
