// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "maidsafe_service_messages.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>

namespace maidsafe {

namespace {

const ::google::protobuf::Descriptor* StoreRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  StoreRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* StoreResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  StoreResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* DeleteRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DeleteRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* DeleteResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DeleteResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* GetRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GetRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* GetResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GetResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* CheckChunkRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CheckChunkRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* CheckChunkResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CheckChunkResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* ValidityCheckRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ValidityCheckRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* ValidityCheckResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ValidityCheckResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* UpdateRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  UpdateRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* UpdateResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  UpdateResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* GetMessagesRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GetMessagesRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* GetMessagesResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GetMessagesResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* SwapChunkRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SwapChunkRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* SwapChunkResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SwapChunkResponse_reflection_ = NULL;

}  // namespace


void protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto_AssignGlobalDescriptors(const ::google::protobuf::FileDescriptor* file) {
  StoreRequest_descriptor_ = file->message_type(0);
  StoreRequest::default_instance_ = new StoreRequest();
  static const int StoreRequest_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StoreRequest, chunkname_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StoreRequest, data_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StoreRequest, public_key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StoreRequest, signed_public_key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StoreRequest, signed_request_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StoreRequest, data_type_),
  };
  StoreRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      StoreRequest_descriptor_,
      StoreRequest::default_instance_,
      StoreRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StoreRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StoreRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(StoreRequest));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    StoreRequest_descriptor_, StoreRequest::default_instance_);
  StoreResponse_descriptor_ = file->message_type(1);
  StoreResponse::default_instance_ = new StoreResponse();
  static const int StoreResponse_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StoreResponse, result_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StoreResponse, pmid_id_),
  };
  StoreResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      StoreResponse_descriptor_,
      StoreResponse::default_instance_,
      StoreResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StoreResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StoreResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(StoreResponse));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    StoreResponse_descriptor_, StoreResponse::default_instance_);
  DeleteRequest_descriptor_ = file->message_type(2);
  DeleteRequest::default_instance_ = new DeleteRequest();
  static const int DeleteRequest_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeleteRequest, chunkname_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeleteRequest, public_key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeleteRequest, signed_public_key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeleteRequest, signed_request_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeleteRequest, data_type_),
  };
  DeleteRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DeleteRequest_descriptor_,
      DeleteRequest::default_instance_,
      DeleteRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeleteRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeleteRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(DeleteRequest));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DeleteRequest_descriptor_, DeleteRequest::default_instance_);
  DeleteResponse_descriptor_ = file->message_type(3);
  DeleteResponse::default_instance_ = new DeleteResponse();
  static const int DeleteResponse_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeleteResponse, result_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeleteResponse, pmid_id_),
  };
  DeleteResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DeleteResponse_descriptor_,
      DeleteResponse::default_instance_,
      DeleteResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeleteResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeleteResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(DeleteResponse));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DeleteResponse_descriptor_, DeleteResponse::default_instance_);
  GetRequest_descriptor_ = file->message_type(4);
  GetRequest::default_instance_ = new GetRequest();
  static const int GetRequest_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetRequest, chunkname_),
  };
  GetRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      GetRequest_descriptor_,
      GetRequest::default_instance_,
      GetRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(GetRequest));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    GetRequest_descriptor_, GetRequest::default_instance_);
  GetResponse_descriptor_ = file->message_type(5);
  GetResponse::default_instance_ = new GetResponse();
  static const int GetResponse_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetResponse, result_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetResponse, content_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetResponse, pmid_id_),
  };
  GetResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      GetResponse_descriptor_,
      GetResponse::default_instance_,
      GetResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(GetResponse));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    GetResponse_descriptor_, GetResponse::default_instance_);
  CheckChunkRequest_descriptor_ = file->message_type(6);
  CheckChunkRequest::default_instance_ = new CheckChunkRequest();
  static const int CheckChunkRequest_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CheckChunkRequest, chunkname_),
  };
  CheckChunkRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CheckChunkRequest_descriptor_,
      CheckChunkRequest::default_instance_,
      CheckChunkRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CheckChunkRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CheckChunkRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(CheckChunkRequest));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CheckChunkRequest_descriptor_, CheckChunkRequest::default_instance_);
  CheckChunkResponse_descriptor_ = file->message_type(7);
  CheckChunkResponse::default_instance_ = new CheckChunkResponse();
  static const int CheckChunkResponse_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CheckChunkResponse, result_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CheckChunkResponse, pmid_id_),
  };
  CheckChunkResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CheckChunkResponse_descriptor_,
      CheckChunkResponse::default_instance_,
      CheckChunkResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CheckChunkResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CheckChunkResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(CheckChunkResponse));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CheckChunkResponse_descriptor_, CheckChunkResponse::default_instance_);
  ValidityCheckRequest_descriptor_ = file->message_type(8);
  ValidityCheckRequest::default_instance_ = new ValidityCheckRequest();
  static const int ValidityCheckRequest_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ValidityCheckRequest, chunkname_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ValidityCheckRequest, random_data_),
  };
  ValidityCheckRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ValidityCheckRequest_descriptor_,
      ValidityCheckRequest::default_instance_,
      ValidityCheckRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ValidityCheckRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ValidityCheckRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(ValidityCheckRequest));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ValidityCheckRequest_descriptor_, ValidityCheckRequest::default_instance_);
  ValidityCheckResponse_descriptor_ = file->message_type(9);
  ValidityCheckResponse::default_instance_ = new ValidityCheckResponse();
  static const int ValidityCheckResponse_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ValidityCheckResponse, result_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ValidityCheckResponse, hash_content_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ValidityCheckResponse, pmid_id_),
  };
  ValidityCheckResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ValidityCheckResponse_descriptor_,
      ValidityCheckResponse::default_instance_,
      ValidityCheckResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ValidityCheckResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ValidityCheckResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(ValidityCheckResponse));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ValidityCheckResponse_descriptor_, ValidityCheckResponse::default_instance_);
  UpdateRequest_descriptor_ = file->message_type(10);
  UpdateRequest::default_instance_ = new UpdateRequest();
  static const int UpdateRequest_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdateRequest, chunkname_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdateRequest, data_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdateRequest, public_key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdateRequest, signed_public_key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdateRequest, signed_request_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdateRequest, data_type_),
  };
  UpdateRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      UpdateRequest_descriptor_,
      UpdateRequest::default_instance_,
      UpdateRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdateRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdateRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(UpdateRequest));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    UpdateRequest_descriptor_, UpdateRequest::default_instance_);
  UpdateResponse_descriptor_ = file->message_type(11);
  UpdateResponse::default_instance_ = new UpdateResponse();
  static const int UpdateResponse_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdateResponse, result_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdateResponse, pmid_id_),
  };
  UpdateResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      UpdateResponse_descriptor_,
      UpdateResponse::default_instance_,
      UpdateResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdateResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdateResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(UpdateResponse));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    UpdateResponse_descriptor_, UpdateResponse::default_instance_);
  GetMessagesRequest_descriptor_ = file->message_type(12);
  GetMessagesRequest::default_instance_ = new GetMessagesRequest();
  static const int GetMessagesRequest_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetMessagesRequest, buffer_packet_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetMessagesRequest, public_key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetMessagesRequest, signed_public_key_),
  };
  GetMessagesRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      GetMessagesRequest_descriptor_,
      GetMessagesRequest::default_instance_,
      GetMessagesRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetMessagesRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetMessagesRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(GetMessagesRequest));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    GetMessagesRequest_descriptor_, GetMessagesRequest::default_instance_);
  GetMessagesResponse_descriptor_ = file->message_type(13);
  GetMessagesResponse::default_instance_ = new GetMessagesResponse();
  static const int GetMessagesResponse_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetMessagesResponse, result_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetMessagesResponse, messages_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetMessagesResponse, pmid_id_),
  };
  GetMessagesResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      GetMessagesResponse_descriptor_,
      GetMessagesResponse::default_instance_,
      GetMessagesResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetMessagesResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetMessagesResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(GetMessagesResponse));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    GetMessagesResponse_descriptor_, GetMessagesResponse::default_instance_);
  SwapChunkRequest_descriptor_ = file->message_type(14);
  SwapChunkRequest::default_instance_ = new SwapChunkRequest();
  static const int SwapChunkRequest_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SwapChunkRequest, request_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SwapChunkRequest, chunkname1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SwapChunkRequest, chunkcontent1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SwapChunkRequest, size1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SwapChunkRequest, chunkname2_),
  };
  SwapChunkRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SwapChunkRequest_descriptor_,
      SwapChunkRequest::default_instance_,
      SwapChunkRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SwapChunkRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SwapChunkRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(SwapChunkRequest));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SwapChunkRequest_descriptor_, SwapChunkRequest::default_instance_);
  SwapChunkResponse_descriptor_ = file->message_type(15);
  SwapChunkResponse::default_instance_ = new SwapChunkResponse();
  static const int SwapChunkResponse_offsets_[9] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SwapChunkResponse, request_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SwapChunkResponse, result_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SwapChunkResponse, chunkname1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SwapChunkResponse, chunkcontent1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SwapChunkResponse, size1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SwapChunkResponse, chunkname2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SwapChunkResponse, chunkcontent2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SwapChunkResponse, size2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SwapChunkResponse, pmid_id_),
  };
  SwapChunkResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SwapChunkResponse_descriptor_,
      SwapChunkResponse::default_instance_,
      SwapChunkResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SwapChunkResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SwapChunkResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(SwapChunkResponse));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SwapChunkResponse_descriptor_, SwapChunkResponse::default_instance_);
  StoreRequest::default_instance_->InitAsDefaultInstance();
  StoreResponse::default_instance_->InitAsDefaultInstance();
  DeleteRequest::default_instance_->InitAsDefaultInstance();
  DeleteResponse::default_instance_->InitAsDefaultInstance();
  GetRequest::default_instance_->InitAsDefaultInstance();
  GetResponse::default_instance_->InitAsDefaultInstance();
  CheckChunkRequest::default_instance_->InitAsDefaultInstance();
  CheckChunkResponse::default_instance_->InitAsDefaultInstance();
  ValidityCheckRequest::default_instance_->InitAsDefaultInstance();
  ValidityCheckResponse::default_instance_->InitAsDefaultInstance();
  UpdateRequest::default_instance_->InitAsDefaultInstance();
  UpdateResponse::default_instance_->InitAsDefaultInstance();
  GetMessagesRequest::default_instance_->InitAsDefaultInstance();
  GetMessagesResponse::default_instance_->InitAsDefaultInstance();
  SwapChunkRequest::default_instance_->InitAsDefaultInstance();
  SwapChunkResponse::default_instance_->InitAsDefaultInstance();
}

void protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  pool->InternalBuildGeneratedFile(
    "\n\037maidsafe_service_messages.proto\022\010maids"
    "afe\"\211\001\n\014StoreRequest\022\021\n\tchunkname\030\001 \002(\014\022"
    "\014\n\004data\030\002 \002(\014\022\022\n\npublic_key\030\003 \002(\014\022\031\n\021sig"
    "ned_public_key\030\004 \002(\014\022\026\n\016signed_request\030\005"
    " \002(\014\022\021\n\tdata_type\030\006 \002(\005\"0\n\rStoreResponse"
    "\022\016\n\006result\030\001 \002(\014\022\017\n\007pmid_id\030\002 \001(\014\"|\n\rDel"
    "eteRequest\022\021\n\tchunkname\030\001 \002(\014\022\022\n\npublic_"
    "key\030\002 \002(\014\022\031\n\021signed_public_key\030\003 \002(\014\022\026\n\016"
    "signed_request\030\004 \002(\014\022\021\n\tdata_type\030\005 \002(\005\""
    "1\n\016DeleteResponse\022\016\n\006result\030\001 \002(\014\022\017\n\007pmi"
    "d_id\030\002 \001(\014\"\037\n\nGetRequest\022\021\n\tchunkname\030\001 "
    "\002(\014\"?\n\013GetResponse\022\016\n\006result\030\001 \002(\014\022\017\n\007co"
    "ntent\030\002 \001(\014\022\017\n\007pmid_id\030\003 \001(\014\"&\n\021CheckChu"
    "nkRequest\022\021\n\tchunkname\030\001 \002(\014\"5\n\022CheckChu"
    "nkResponse\022\016\n\006result\030\001 \002(\014\022\017\n\007pmid_id\030\002 "
    "\002(\014\">\n\024ValidityCheckRequest\022\021\n\tchunkname"
    "\030\001 \002(\014\022\023\n\013random_data\030\002 \002(\014\"N\n\025ValidityC"
    "heckResponse\022\016\n\006result\030\001 \002(\014\022\024\n\014hash_con"
    "tent\030\002 \001(\014\022\017\n\007pmid_id\030\003 \002(\014\"\212\001\n\rUpdateRe"
    "quest\022\021\n\tchunkname\030\001 \002(\014\022\014\n\004data\030\002 \002(\014\022\022"
    "\n\npublic_key\030\003 \002(\014\022\031\n\021signed_public_key\030"
    "\004 \002(\014\022\026\n\016signed_request\030\005 \002(\014\022\021\n\tdata_ty"
    "pe\030\006 \002(\005\"1\n\016UpdateResponse\022\016\n\006result\030\001 \002"
    "(\014\022\017\n\007pmid_id\030\002 \001(\014\"_\n\022GetMessagesReques"
    "t\022\032\n\022buffer_packet_name\030\001 \002(\014\022\022\n\npublic_"
    "key\030\002 \002(\014\022\031\n\021signed_public_key\030\003 \002(\014\"H\n\023"
    "GetMessagesResponse\022\016\n\006result\030\001 \002(\014\022\020\n\010m"
    "essages\030\002 \003(\014\022\017\n\007pmid_id\030\003 \001(\014\"v\n\020SwapCh"
    "unkRequest\022\024\n\014request_type\030\001 \002(\005\022\022\n\nchun"
    "kname1\030\002 \002(\014\022\025\n\rchunkcontent1\030\003 \001(\014\022\r\n\005s"
    "ize1\030\004 \001(\005\022\022\n\nchunkname2\030\005 \001(\014\"\276\001\n\021SwapC"
    "hunkResponse\022\024\n\014request_type\030\001 \002(\005\022\016\n\006re"
    "sult\030\002 \002(\014\022\022\n\nchunkname1\030\003 \001(\014\022\025\n\rchunkc"
    "ontent1\030\004 \001(\014\022\r\n\005size1\030\005 \001(\005\022\022\n\nchunknam"
    "e2\030\006 \001(\014\022\025\n\rchunkcontent2\030\007 \001(\014\022\r\n\005size2"
    "\030\010 \001(\005\022\017\n\007pmid_id\030\t \002(\014", 1423,
  &protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto_AssignGlobalDescriptors);
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_maidsafe_5fservice_5fmessages_2eproto {
  StaticDescriptorInitializer_maidsafe_5fservice_5fmessages_2eproto() {
    protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  }
} static_descriptor_initializer_maidsafe_5fservice_5fmessages_2eproto_;


// ===================================================================

const ::std::string StoreRequest::_default_chunkname_;
const ::std::string StoreRequest::_default_data_;
const ::std::string StoreRequest::_default_public_key_;
const ::std::string StoreRequest::_default_signed_public_key_;
const ::std::string StoreRequest::_default_signed_request_;

StoreRequest::StoreRequest()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    chunkname_(const_cast< ::std::string*>(&_default_chunkname_)),
    data_(const_cast< ::std::string*>(&_default_data_)),
    public_key_(const_cast< ::std::string*>(&_default_public_key_)),
    signed_public_key_(const_cast< ::std::string*>(&_default_signed_public_key_)),
    signed_request_(const_cast< ::std::string*>(&_default_signed_request_)),
    data_type_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void StoreRequest::InitAsDefaultInstance() {}

StoreRequest::StoreRequest(const StoreRequest& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    chunkname_(const_cast< ::std::string*>(&_default_chunkname_)),
    data_(const_cast< ::std::string*>(&_default_data_)),
    public_key_(const_cast< ::std::string*>(&_default_public_key_)),
    signed_public_key_(const_cast< ::std::string*>(&_default_signed_public_key_)),
    signed_request_(const_cast< ::std::string*>(&_default_signed_request_)),
    data_type_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

StoreRequest::~StoreRequest() {
  if (chunkname_ != &_default_chunkname_) {
    delete chunkname_;
  }
  if (data_ != &_default_data_) {
    delete data_;
  }
  if (public_key_ != &_default_public_key_) {
    delete public_key_;
  }
  if (signed_public_key_ != &_default_signed_public_key_) {
    delete signed_public_key_;
  }
  if (signed_request_ != &_default_signed_request_) {
    delete signed_request_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* StoreRequest::descriptor() {
  if (StoreRequest_descriptor_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return StoreRequest_descriptor_;
}

const StoreRequest& StoreRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return *default_instance_;
}

StoreRequest* StoreRequest::default_instance_ = NULL;

StoreRequest* StoreRequest::New() const {
  return new StoreRequest;
}

const ::google::protobuf::Descriptor* StoreRequest::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* StoreRequest::GetReflection() const {
  if (StoreRequest_reflection_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return StoreRequest_reflection_;
}

// ===================================================================

const ::std::string StoreResponse::_default_result_;
const ::std::string StoreResponse::_default_pmid_id_;
StoreResponse::StoreResponse()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    result_(const_cast< ::std::string*>(&_default_result_)),
    pmid_id_(const_cast< ::std::string*>(&_default_pmid_id_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void StoreResponse::InitAsDefaultInstance() {}

StoreResponse::StoreResponse(const StoreResponse& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    result_(const_cast< ::std::string*>(&_default_result_)),
    pmid_id_(const_cast< ::std::string*>(&_default_pmid_id_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

StoreResponse::~StoreResponse() {
  if (result_ != &_default_result_) {
    delete result_;
  }
  if (pmid_id_ != &_default_pmid_id_) {
    delete pmid_id_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* StoreResponse::descriptor() {
  if (StoreResponse_descriptor_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return StoreResponse_descriptor_;
}

const StoreResponse& StoreResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return *default_instance_;
}

StoreResponse* StoreResponse::default_instance_ = NULL;

StoreResponse* StoreResponse::New() const {
  return new StoreResponse;
}

const ::google::protobuf::Descriptor* StoreResponse::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* StoreResponse::GetReflection() const {
  if (StoreResponse_reflection_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return StoreResponse_reflection_;
}

// ===================================================================

const ::std::string DeleteRequest::_default_chunkname_;
const ::std::string DeleteRequest::_default_public_key_;
const ::std::string DeleteRequest::_default_signed_public_key_;
const ::std::string DeleteRequest::_default_signed_request_;

DeleteRequest::DeleteRequest()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    chunkname_(const_cast< ::std::string*>(&_default_chunkname_)),
    public_key_(const_cast< ::std::string*>(&_default_public_key_)),
    signed_public_key_(const_cast< ::std::string*>(&_default_signed_public_key_)),
    signed_request_(const_cast< ::std::string*>(&_default_signed_request_)),
    data_type_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void DeleteRequest::InitAsDefaultInstance() {}

DeleteRequest::DeleteRequest(const DeleteRequest& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    chunkname_(const_cast< ::std::string*>(&_default_chunkname_)),
    public_key_(const_cast< ::std::string*>(&_default_public_key_)),
    signed_public_key_(const_cast< ::std::string*>(&_default_signed_public_key_)),
    signed_request_(const_cast< ::std::string*>(&_default_signed_request_)),
    data_type_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

DeleteRequest::~DeleteRequest() {
  if (chunkname_ != &_default_chunkname_) {
    delete chunkname_;
  }
  if (public_key_ != &_default_public_key_) {
    delete public_key_;
  }
  if (signed_public_key_ != &_default_signed_public_key_) {
    delete signed_public_key_;
  }
  if (signed_request_ != &_default_signed_request_) {
    delete signed_request_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* DeleteRequest::descriptor() {
  if (DeleteRequest_descriptor_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return DeleteRequest_descriptor_;
}

const DeleteRequest& DeleteRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return *default_instance_;
}

DeleteRequest* DeleteRequest::default_instance_ = NULL;

DeleteRequest* DeleteRequest::New() const {
  return new DeleteRequest;
}

const ::google::protobuf::Descriptor* DeleteRequest::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* DeleteRequest::GetReflection() const {
  if (DeleteRequest_reflection_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return DeleteRequest_reflection_;
}

// ===================================================================

const ::std::string DeleteResponse::_default_result_;
const ::std::string DeleteResponse::_default_pmid_id_;
DeleteResponse::DeleteResponse()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    result_(const_cast< ::std::string*>(&_default_result_)),
    pmid_id_(const_cast< ::std::string*>(&_default_pmid_id_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void DeleteResponse::InitAsDefaultInstance() {}

DeleteResponse::DeleteResponse(const DeleteResponse& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    result_(const_cast< ::std::string*>(&_default_result_)),
    pmid_id_(const_cast< ::std::string*>(&_default_pmid_id_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

DeleteResponse::~DeleteResponse() {
  if (result_ != &_default_result_) {
    delete result_;
  }
  if (pmid_id_ != &_default_pmid_id_) {
    delete pmid_id_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* DeleteResponse::descriptor() {
  if (DeleteResponse_descriptor_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return DeleteResponse_descriptor_;
}

const DeleteResponse& DeleteResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return *default_instance_;
}

DeleteResponse* DeleteResponse::default_instance_ = NULL;

DeleteResponse* DeleteResponse::New() const {
  return new DeleteResponse;
}

const ::google::protobuf::Descriptor* DeleteResponse::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* DeleteResponse::GetReflection() const {
  if (DeleteResponse_reflection_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return DeleteResponse_reflection_;
}

// ===================================================================

const ::std::string GetRequest::_default_chunkname_;
GetRequest::GetRequest()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    chunkname_(const_cast< ::std::string*>(&_default_chunkname_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void GetRequest::InitAsDefaultInstance() {}

GetRequest::GetRequest(const GetRequest& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    chunkname_(const_cast< ::std::string*>(&_default_chunkname_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

GetRequest::~GetRequest() {
  if (chunkname_ != &_default_chunkname_) {
    delete chunkname_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* GetRequest::descriptor() {
  if (GetRequest_descriptor_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return GetRequest_descriptor_;
}

const GetRequest& GetRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return *default_instance_;
}

GetRequest* GetRequest::default_instance_ = NULL;

GetRequest* GetRequest::New() const {
  return new GetRequest;
}

const ::google::protobuf::Descriptor* GetRequest::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* GetRequest::GetReflection() const {
  if (GetRequest_reflection_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return GetRequest_reflection_;
}

// ===================================================================

const ::std::string GetResponse::_default_result_;
const ::std::string GetResponse::_default_content_;
const ::std::string GetResponse::_default_pmid_id_;
GetResponse::GetResponse()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    result_(const_cast< ::std::string*>(&_default_result_)),
    content_(const_cast< ::std::string*>(&_default_content_)),
    pmid_id_(const_cast< ::std::string*>(&_default_pmid_id_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void GetResponse::InitAsDefaultInstance() {}

GetResponse::GetResponse(const GetResponse& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    result_(const_cast< ::std::string*>(&_default_result_)),
    content_(const_cast< ::std::string*>(&_default_content_)),
    pmid_id_(const_cast< ::std::string*>(&_default_pmid_id_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

GetResponse::~GetResponse() {
  if (result_ != &_default_result_) {
    delete result_;
  }
  if (content_ != &_default_content_) {
    delete content_;
  }
  if (pmid_id_ != &_default_pmid_id_) {
    delete pmid_id_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* GetResponse::descriptor() {
  if (GetResponse_descriptor_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return GetResponse_descriptor_;
}

const GetResponse& GetResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return *default_instance_;
}

GetResponse* GetResponse::default_instance_ = NULL;

GetResponse* GetResponse::New() const {
  return new GetResponse;
}

const ::google::protobuf::Descriptor* GetResponse::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* GetResponse::GetReflection() const {
  if (GetResponse_reflection_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return GetResponse_reflection_;
}

// ===================================================================

const ::std::string CheckChunkRequest::_default_chunkname_;
CheckChunkRequest::CheckChunkRequest()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    chunkname_(const_cast< ::std::string*>(&_default_chunkname_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void CheckChunkRequest::InitAsDefaultInstance() {}

CheckChunkRequest::CheckChunkRequest(const CheckChunkRequest& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    chunkname_(const_cast< ::std::string*>(&_default_chunkname_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

CheckChunkRequest::~CheckChunkRequest() {
  if (chunkname_ != &_default_chunkname_) {
    delete chunkname_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* CheckChunkRequest::descriptor() {
  if (CheckChunkRequest_descriptor_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return CheckChunkRequest_descriptor_;
}

const CheckChunkRequest& CheckChunkRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return *default_instance_;
}

CheckChunkRequest* CheckChunkRequest::default_instance_ = NULL;

CheckChunkRequest* CheckChunkRequest::New() const {
  return new CheckChunkRequest;
}

const ::google::protobuf::Descriptor* CheckChunkRequest::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* CheckChunkRequest::GetReflection() const {
  if (CheckChunkRequest_reflection_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return CheckChunkRequest_reflection_;
}

// ===================================================================

const ::std::string CheckChunkResponse::_default_result_;
const ::std::string CheckChunkResponse::_default_pmid_id_;
CheckChunkResponse::CheckChunkResponse()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    result_(const_cast< ::std::string*>(&_default_result_)),
    pmid_id_(const_cast< ::std::string*>(&_default_pmid_id_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void CheckChunkResponse::InitAsDefaultInstance() {}

CheckChunkResponse::CheckChunkResponse(const CheckChunkResponse& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    result_(const_cast< ::std::string*>(&_default_result_)),
    pmid_id_(const_cast< ::std::string*>(&_default_pmid_id_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

CheckChunkResponse::~CheckChunkResponse() {
  if (result_ != &_default_result_) {
    delete result_;
  }
  if (pmid_id_ != &_default_pmid_id_) {
    delete pmid_id_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* CheckChunkResponse::descriptor() {
  if (CheckChunkResponse_descriptor_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return CheckChunkResponse_descriptor_;
}

const CheckChunkResponse& CheckChunkResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return *default_instance_;
}

CheckChunkResponse* CheckChunkResponse::default_instance_ = NULL;

CheckChunkResponse* CheckChunkResponse::New() const {
  return new CheckChunkResponse;
}

const ::google::protobuf::Descriptor* CheckChunkResponse::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* CheckChunkResponse::GetReflection() const {
  if (CheckChunkResponse_reflection_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return CheckChunkResponse_reflection_;
}

// ===================================================================

const ::std::string ValidityCheckRequest::_default_chunkname_;
const ::std::string ValidityCheckRequest::_default_random_data_;
ValidityCheckRequest::ValidityCheckRequest()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    chunkname_(const_cast< ::std::string*>(&_default_chunkname_)),
    random_data_(const_cast< ::std::string*>(&_default_random_data_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void ValidityCheckRequest::InitAsDefaultInstance() {}

ValidityCheckRequest::ValidityCheckRequest(const ValidityCheckRequest& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    chunkname_(const_cast< ::std::string*>(&_default_chunkname_)),
    random_data_(const_cast< ::std::string*>(&_default_random_data_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

ValidityCheckRequest::~ValidityCheckRequest() {
  if (chunkname_ != &_default_chunkname_) {
    delete chunkname_;
  }
  if (random_data_ != &_default_random_data_) {
    delete random_data_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* ValidityCheckRequest::descriptor() {
  if (ValidityCheckRequest_descriptor_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return ValidityCheckRequest_descriptor_;
}

const ValidityCheckRequest& ValidityCheckRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return *default_instance_;
}

ValidityCheckRequest* ValidityCheckRequest::default_instance_ = NULL;

ValidityCheckRequest* ValidityCheckRequest::New() const {
  return new ValidityCheckRequest;
}

const ::google::protobuf::Descriptor* ValidityCheckRequest::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* ValidityCheckRequest::GetReflection() const {
  if (ValidityCheckRequest_reflection_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return ValidityCheckRequest_reflection_;
}

// ===================================================================

const ::std::string ValidityCheckResponse::_default_result_;
const ::std::string ValidityCheckResponse::_default_hash_content_;
const ::std::string ValidityCheckResponse::_default_pmid_id_;
ValidityCheckResponse::ValidityCheckResponse()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    result_(const_cast< ::std::string*>(&_default_result_)),
    hash_content_(const_cast< ::std::string*>(&_default_hash_content_)),
    pmid_id_(const_cast< ::std::string*>(&_default_pmid_id_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void ValidityCheckResponse::InitAsDefaultInstance() {}

ValidityCheckResponse::ValidityCheckResponse(const ValidityCheckResponse& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    result_(const_cast< ::std::string*>(&_default_result_)),
    hash_content_(const_cast< ::std::string*>(&_default_hash_content_)),
    pmid_id_(const_cast< ::std::string*>(&_default_pmid_id_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

ValidityCheckResponse::~ValidityCheckResponse() {
  if (result_ != &_default_result_) {
    delete result_;
  }
  if (hash_content_ != &_default_hash_content_) {
    delete hash_content_;
  }
  if (pmid_id_ != &_default_pmid_id_) {
    delete pmid_id_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* ValidityCheckResponse::descriptor() {
  if (ValidityCheckResponse_descriptor_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return ValidityCheckResponse_descriptor_;
}

const ValidityCheckResponse& ValidityCheckResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return *default_instance_;
}

ValidityCheckResponse* ValidityCheckResponse::default_instance_ = NULL;

ValidityCheckResponse* ValidityCheckResponse::New() const {
  return new ValidityCheckResponse;
}

const ::google::protobuf::Descriptor* ValidityCheckResponse::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* ValidityCheckResponse::GetReflection() const {
  if (ValidityCheckResponse_reflection_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return ValidityCheckResponse_reflection_;
}

// ===================================================================

const ::std::string UpdateRequest::_default_chunkname_;
const ::std::string UpdateRequest::_default_data_;
const ::std::string UpdateRequest::_default_public_key_;
const ::std::string UpdateRequest::_default_signed_public_key_;
const ::std::string UpdateRequest::_default_signed_request_;

UpdateRequest::UpdateRequest()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    chunkname_(const_cast< ::std::string*>(&_default_chunkname_)),
    data_(const_cast< ::std::string*>(&_default_data_)),
    public_key_(const_cast< ::std::string*>(&_default_public_key_)),
    signed_public_key_(const_cast< ::std::string*>(&_default_signed_public_key_)),
    signed_request_(const_cast< ::std::string*>(&_default_signed_request_)),
    data_type_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void UpdateRequest::InitAsDefaultInstance() {}

UpdateRequest::UpdateRequest(const UpdateRequest& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    chunkname_(const_cast< ::std::string*>(&_default_chunkname_)),
    data_(const_cast< ::std::string*>(&_default_data_)),
    public_key_(const_cast< ::std::string*>(&_default_public_key_)),
    signed_public_key_(const_cast< ::std::string*>(&_default_signed_public_key_)),
    signed_request_(const_cast< ::std::string*>(&_default_signed_request_)),
    data_type_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

UpdateRequest::~UpdateRequest() {
  if (chunkname_ != &_default_chunkname_) {
    delete chunkname_;
  }
  if (data_ != &_default_data_) {
    delete data_;
  }
  if (public_key_ != &_default_public_key_) {
    delete public_key_;
  }
  if (signed_public_key_ != &_default_signed_public_key_) {
    delete signed_public_key_;
  }
  if (signed_request_ != &_default_signed_request_) {
    delete signed_request_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* UpdateRequest::descriptor() {
  if (UpdateRequest_descriptor_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return UpdateRequest_descriptor_;
}

const UpdateRequest& UpdateRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return *default_instance_;
}

UpdateRequest* UpdateRequest::default_instance_ = NULL;

UpdateRequest* UpdateRequest::New() const {
  return new UpdateRequest;
}

const ::google::protobuf::Descriptor* UpdateRequest::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* UpdateRequest::GetReflection() const {
  if (UpdateRequest_reflection_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return UpdateRequest_reflection_;
}

// ===================================================================

const ::std::string UpdateResponse::_default_result_;
const ::std::string UpdateResponse::_default_pmid_id_;
UpdateResponse::UpdateResponse()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    result_(const_cast< ::std::string*>(&_default_result_)),
    pmid_id_(const_cast< ::std::string*>(&_default_pmid_id_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void UpdateResponse::InitAsDefaultInstance() {}

UpdateResponse::UpdateResponse(const UpdateResponse& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    result_(const_cast< ::std::string*>(&_default_result_)),
    pmid_id_(const_cast< ::std::string*>(&_default_pmid_id_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

UpdateResponse::~UpdateResponse() {
  if (result_ != &_default_result_) {
    delete result_;
  }
  if (pmid_id_ != &_default_pmid_id_) {
    delete pmid_id_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* UpdateResponse::descriptor() {
  if (UpdateResponse_descriptor_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return UpdateResponse_descriptor_;
}

const UpdateResponse& UpdateResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return *default_instance_;
}

UpdateResponse* UpdateResponse::default_instance_ = NULL;

UpdateResponse* UpdateResponse::New() const {
  return new UpdateResponse;
}

const ::google::protobuf::Descriptor* UpdateResponse::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* UpdateResponse::GetReflection() const {
  if (UpdateResponse_reflection_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return UpdateResponse_reflection_;
}

// ===================================================================

const ::std::string GetMessagesRequest::_default_buffer_packet_name_;
const ::std::string GetMessagesRequest::_default_public_key_;
const ::std::string GetMessagesRequest::_default_signed_public_key_;
GetMessagesRequest::GetMessagesRequest()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    buffer_packet_name_(const_cast< ::std::string*>(&_default_buffer_packet_name_)),
    public_key_(const_cast< ::std::string*>(&_default_public_key_)),
    signed_public_key_(const_cast< ::std::string*>(&_default_signed_public_key_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void GetMessagesRequest::InitAsDefaultInstance() {}

GetMessagesRequest::GetMessagesRequest(const GetMessagesRequest& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    buffer_packet_name_(const_cast< ::std::string*>(&_default_buffer_packet_name_)),
    public_key_(const_cast< ::std::string*>(&_default_public_key_)),
    signed_public_key_(const_cast< ::std::string*>(&_default_signed_public_key_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

GetMessagesRequest::~GetMessagesRequest() {
  if (buffer_packet_name_ != &_default_buffer_packet_name_) {
    delete buffer_packet_name_;
  }
  if (public_key_ != &_default_public_key_) {
    delete public_key_;
  }
  if (signed_public_key_ != &_default_signed_public_key_) {
    delete signed_public_key_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* GetMessagesRequest::descriptor() {
  if (GetMessagesRequest_descriptor_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return GetMessagesRequest_descriptor_;
}

const GetMessagesRequest& GetMessagesRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return *default_instance_;
}

GetMessagesRequest* GetMessagesRequest::default_instance_ = NULL;

GetMessagesRequest* GetMessagesRequest::New() const {
  return new GetMessagesRequest;
}

const ::google::protobuf::Descriptor* GetMessagesRequest::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* GetMessagesRequest::GetReflection() const {
  if (GetMessagesRequest_reflection_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return GetMessagesRequest_reflection_;
}

// ===================================================================

const ::std::string GetMessagesResponse::_default_result_;

const ::std::string GetMessagesResponse::_default_pmid_id_;
GetMessagesResponse::GetMessagesResponse()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    result_(const_cast< ::std::string*>(&_default_result_)),
    pmid_id_(const_cast< ::std::string*>(&_default_pmid_id_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void GetMessagesResponse::InitAsDefaultInstance() {}

GetMessagesResponse::GetMessagesResponse(const GetMessagesResponse& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    result_(const_cast< ::std::string*>(&_default_result_)),
    pmid_id_(const_cast< ::std::string*>(&_default_pmid_id_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

GetMessagesResponse::~GetMessagesResponse() {
  if (result_ != &_default_result_) {
    delete result_;
  }
  if (pmid_id_ != &_default_pmid_id_) {
    delete pmid_id_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* GetMessagesResponse::descriptor() {
  if (GetMessagesResponse_descriptor_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return GetMessagesResponse_descriptor_;
}

const GetMessagesResponse& GetMessagesResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return *default_instance_;
}

GetMessagesResponse* GetMessagesResponse::default_instance_ = NULL;

GetMessagesResponse* GetMessagesResponse::New() const {
  return new GetMessagesResponse;
}

const ::google::protobuf::Descriptor* GetMessagesResponse::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* GetMessagesResponse::GetReflection() const {
  if (GetMessagesResponse_reflection_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return GetMessagesResponse_reflection_;
}

// ===================================================================


const ::std::string SwapChunkRequest::_default_chunkname1_;
const ::std::string SwapChunkRequest::_default_chunkcontent1_;

const ::std::string SwapChunkRequest::_default_chunkname2_;
SwapChunkRequest::SwapChunkRequest()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    request_type_(0),
    chunkname1_(const_cast< ::std::string*>(&_default_chunkname1_)),
    chunkcontent1_(const_cast< ::std::string*>(&_default_chunkcontent1_)),
    size1_(0),
    chunkname2_(const_cast< ::std::string*>(&_default_chunkname2_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void SwapChunkRequest::InitAsDefaultInstance() {}

SwapChunkRequest::SwapChunkRequest(const SwapChunkRequest& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    request_type_(0),
    chunkname1_(const_cast< ::std::string*>(&_default_chunkname1_)),
    chunkcontent1_(const_cast< ::std::string*>(&_default_chunkcontent1_)),
    size1_(0),
    chunkname2_(const_cast< ::std::string*>(&_default_chunkname2_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

SwapChunkRequest::~SwapChunkRequest() {
  if (chunkname1_ != &_default_chunkname1_) {
    delete chunkname1_;
  }
  if (chunkcontent1_ != &_default_chunkcontent1_) {
    delete chunkcontent1_;
  }
  if (chunkname2_ != &_default_chunkname2_) {
    delete chunkname2_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* SwapChunkRequest::descriptor() {
  if (SwapChunkRequest_descriptor_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return SwapChunkRequest_descriptor_;
}

const SwapChunkRequest& SwapChunkRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return *default_instance_;
}

SwapChunkRequest* SwapChunkRequest::default_instance_ = NULL;

SwapChunkRequest* SwapChunkRequest::New() const {
  return new SwapChunkRequest;
}

const ::google::protobuf::Descriptor* SwapChunkRequest::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* SwapChunkRequest::GetReflection() const {
  if (SwapChunkRequest_reflection_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return SwapChunkRequest_reflection_;
}

// ===================================================================


const ::std::string SwapChunkResponse::_default_result_;
const ::std::string SwapChunkResponse::_default_chunkname1_;
const ::std::string SwapChunkResponse::_default_chunkcontent1_;

const ::std::string SwapChunkResponse::_default_chunkname2_;
const ::std::string SwapChunkResponse::_default_chunkcontent2_;

const ::std::string SwapChunkResponse::_default_pmid_id_;
SwapChunkResponse::SwapChunkResponse()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    request_type_(0),
    result_(const_cast< ::std::string*>(&_default_result_)),
    chunkname1_(const_cast< ::std::string*>(&_default_chunkname1_)),
    chunkcontent1_(const_cast< ::std::string*>(&_default_chunkcontent1_)),
    size1_(0),
    chunkname2_(const_cast< ::std::string*>(&_default_chunkname2_)),
    chunkcontent2_(const_cast< ::std::string*>(&_default_chunkcontent2_)),
    size2_(0),
    pmid_id_(const_cast< ::std::string*>(&_default_pmid_id_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void SwapChunkResponse::InitAsDefaultInstance() {}

SwapChunkResponse::SwapChunkResponse(const SwapChunkResponse& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    request_type_(0),
    result_(const_cast< ::std::string*>(&_default_result_)),
    chunkname1_(const_cast< ::std::string*>(&_default_chunkname1_)),
    chunkcontent1_(const_cast< ::std::string*>(&_default_chunkcontent1_)),
    size1_(0),
    chunkname2_(const_cast< ::std::string*>(&_default_chunkname2_)),
    chunkcontent2_(const_cast< ::std::string*>(&_default_chunkcontent2_)),
    size2_(0),
    pmid_id_(const_cast< ::std::string*>(&_default_pmid_id_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

SwapChunkResponse::~SwapChunkResponse() {
  if (result_ != &_default_result_) {
    delete result_;
  }
  if (chunkname1_ != &_default_chunkname1_) {
    delete chunkname1_;
  }
  if (chunkcontent1_ != &_default_chunkcontent1_) {
    delete chunkcontent1_;
  }
  if (chunkname2_ != &_default_chunkname2_) {
    delete chunkname2_;
  }
  if (chunkcontent2_ != &_default_chunkcontent2_) {
    delete chunkcontent2_;
  }
  if (pmid_id_ != &_default_pmid_id_) {
    delete pmid_id_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* SwapChunkResponse::descriptor() {
  if (SwapChunkResponse_descriptor_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return SwapChunkResponse_descriptor_;
}

const SwapChunkResponse& SwapChunkResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return *default_instance_;
}

SwapChunkResponse* SwapChunkResponse::default_instance_ = NULL;

SwapChunkResponse* SwapChunkResponse::New() const {
  return new SwapChunkResponse;
}

const ::google::protobuf::Descriptor* SwapChunkResponse::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* SwapChunkResponse::GetReflection() const {
  if (SwapChunkResponse_reflection_ == NULL) protobuf_BuildDesc_maidsafe_5fservice_5fmessages_2eproto();
  return SwapChunkResponse_reflection_;
}

}  // namespace maidsafe
