// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "packet.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>

namespace packethandler {

namespace {

const ::google::protobuf::Descriptor* GenericPacket_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GenericPacket_reflection_ = NULL;
const ::google::protobuf::Descriptor* BufferPacketInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  BufferPacketInfo_reflection_ = NULL;
const ::google::protobuf::Descriptor* BufferPacketMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  BufferPacketMessage_reflection_ = NULL;
const ::google::protobuf::Descriptor* BufferPacket_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  BufferPacket_reflection_ = NULL;
const ::google::protobuf::Descriptor* ValidatedBufferPacketMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ValidatedBufferPacketMessage_reflection_ = NULL;
const ::google::protobuf::Descriptor* ContactInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ContactInfo_reflection_ = NULL;
const ::google::protobuf::Descriptor* ContactNotification_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ContactNotification_reflection_ = NULL;
const ::google::protobuf::Descriptor* InstantFileNotification_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  InstantFileNotification_reflection_ = NULL;
const ::google::protobuf::Descriptor* PrivateShareNotification_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PrivateShareNotification_reflection_ = NULL;
const ::google::protobuf::Descriptor* InstantMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  InstantMessage_reflection_ = NULL;
const ::google::protobuf::Descriptor* StoreMessagesResult_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  StoreMessagesResult_reflection_ = NULL;
const ::google::protobuf::Descriptor* CreateMSIDResult_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CreateMSIDResult_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* MessageType_descriptor_ = NULL;

}  // namespace


void protobuf_BuildDesc_packet_2eproto_AssignGlobalDescriptors(const ::google::protobuf::FileDescriptor* file) {
  GenericPacket_descriptor_ = file->message_type(0);
  GenericPacket::default_instance_ = new GenericPacket();
  static const int GenericPacket_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GenericPacket, data_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GenericPacket, signature_),
  };
  GenericPacket_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      GenericPacket_descriptor_,
      GenericPacket::default_instance_,
      GenericPacket_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GenericPacket, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GenericPacket, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(GenericPacket));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    GenericPacket_descriptor_, GenericPacket::default_instance_);
  BufferPacketInfo_descriptor_ = file->message_type(1);
  BufferPacketInfo::default_instance_ = new BufferPacketInfo();
  static const int BufferPacketInfo_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BufferPacketInfo, owner_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BufferPacketInfo, ownerpublickey_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BufferPacketInfo, users_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BufferPacketInfo, online_),
  };
  BufferPacketInfo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      BufferPacketInfo_descriptor_,
      BufferPacketInfo::default_instance_,
      BufferPacketInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BufferPacketInfo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BufferPacketInfo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(BufferPacketInfo));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    BufferPacketInfo_descriptor_, BufferPacketInfo::default_instance_);
  BufferPacketMessage_descriptor_ = file->message_type(2);
  BufferPacketMessage::default_instance_ = new BufferPacketMessage();
  static const int BufferPacketMessage_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BufferPacketMessage, sender_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BufferPacketMessage, sender_public_key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BufferPacketMessage, rsaenc_key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BufferPacketMessage, aesenc_message_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BufferPacketMessage, type_),
  };
  BufferPacketMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      BufferPacketMessage_descriptor_,
      BufferPacketMessage::default_instance_,
      BufferPacketMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BufferPacketMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BufferPacketMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(BufferPacketMessage));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    BufferPacketMessage_descriptor_, BufferPacketMessage::default_instance_);
  BufferPacket_descriptor_ = file->message_type(3);
  BufferPacket::default_instance_ = new BufferPacket();
  static const int BufferPacket_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BufferPacket, owner_info_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BufferPacket, messages_),
  };
  BufferPacket_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      BufferPacket_descriptor_,
      BufferPacket::default_instance_,
      BufferPacket_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BufferPacket, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BufferPacket, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(BufferPacket));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    BufferPacket_descriptor_, BufferPacket::default_instance_);
  ValidatedBufferPacketMessage_descriptor_ = file->message_type(4);
  ValidatedBufferPacketMessage::default_instance_ = new ValidatedBufferPacketMessage();
  static const int ValidatedBufferPacketMessage_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ValidatedBufferPacketMessage, sender_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ValidatedBufferPacketMessage, message_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ValidatedBufferPacketMessage, index_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ValidatedBufferPacketMessage, type_),
  };
  ValidatedBufferPacketMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ValidatedBufferPacketMessage_descriptor_,
      ValidatedBufferPacketMessage::default_instance_,
      ValidatedBufferPacketMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ValidatedBufferPacketMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ValidatedBufferPacketMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(ValidatedBufferPacketMessage));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ValidatedBufferPacketMessage_descriptor_, ValidatedBufferPacketMessage::default_instance_);
  ContactInfo_descriptor_ = file->message_type(5);
  ContactInfo::default_instance_ = new ContactInfo();
  static const int ContactInfo_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContactInfo, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContactInfo, birthday_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContactInfo, office_number_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContactInfo, gender_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContactInfo, country_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContactInfo, city_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContactInfo, language_),
  };
  ContactInfo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ContactInfo_descriptor_,
      ContactInfo::default_instance_,
      ContactInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContactInfo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContactInfo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(ContactInfo));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ContactInfo_descriptor_, ContactInfo::default_instance_);
  ContactNotification_descriptor_ = file->message_type(6);
  ContactNotification::default_instance_ = new ContactNotification();
  static const int ContactNotification_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContactNotification, action_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContactNotification, contact_),
  };
  ContactNotification_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ContactNotification_descriptor_,
      ContactNotification::default_instance_,
      ContactNotification_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContactNotification, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContactNotification, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(ContactNotification));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ContactNotification_descriptor_, ContactNotification::default_instance_);
  InstantFileNotification_descriptor_ = file->message_type(7);
  InstantFileNotification::default_instance_ = new InstantFileNotification();
  static const int InstantFileNotification_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(InstantFileNotification, ser_mdm_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(InstantFileNotification, ser_dm_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(InstantFileNotification, filename_),
  };
  InstantFileNotification_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      InstantFileNotification_descriptor_,
      InstantFileNotification::default_instance_,
      InstantFileNotification_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(InstantFileNotification, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(InstantFileNotification, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(InstantFileNotification));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    InstantFileNotification_descriptor_, InstantFileNotification::default_instance_);
  PrivateShareNotification_descriptor_ = file->message_type(8);
  PrivateShareNotification::default_instance_ = new PrivateShareNotification();
  static const int PrivateShareNotification_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PrivateShareNotification, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PrivateShareNotification, msid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PrivateShareNotification, public_key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PrivateShareNotification, private_key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PrivateShareNotification, admins_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PrivateShareNotification, readonlys_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PrivateShareNotification, dir_db_key_),
  };
  PrivateShareNotification_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PrivateShareNotification_descriptor_,
      PrivateShareNotification::default_instance_,
      PrivateShareNotification_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PrivateShareNotification, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PrivateShareNotification, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(PrivateShareNotification));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PrivateShareNotification_descriptor_, PrivateShareNotification::default_instance_);
  InstantMessage_descriptor_ = file->message_type(9);
  InstantMessage::default_instance_ = new InstantMessage();
  static const int InstantMessage_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(InstantMessage, sender_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(InstantMessage, message_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(InstantMessage, date_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(InstantMessage, contact_notification_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(InstantMessage, instantfile_notification_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(InstantMessage, privateshare_notification_),
  };
  InstantMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      InstantMessage_descriptor_,
      InstantMessage::default_instance_,
      InstantMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(InstantMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(InstantMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(InstantMessage));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    InstantMessage_descriptor_, InstantMessage::default_instance_);
  StoreMessagesResult_descriptor_ = file->message_type(10);
  StoreMessagesResult::default_instance_ = new StoreMessagesResult();
  static const int StoreMessagesResult_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StoreMessagesResult, result_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StoreMessagesResult, stored_msgs_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StoreMessagesResult, failed_),
  };
  StoreMessagesResult_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      StoreMessagesResult_descriptor_,
      StoreMessagesResult::default_instance_,
      StoreMessagesResult_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StoreMessagesResult, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StoreMessagesResult, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(StoreMessagesResult));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    StoreMessagesResult_descriptor_, StoreMessagesResult::default_instance_);
  CreateMSIDResult_descriptor_ = file->message_type(11);
  CreateMSIDResult::default_instance_ = new CreateMSIDResult();
  static const int CreateMSIDResult_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CreateMSIDResult, result_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CreateMSIDResult, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CreateMSIDResult, private_key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CreateMSIDResult, public_key_),
  };
  CreateMSIDResult_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CreateMSIDResult_descriptor_,
      CreateMSIDResult::default_instance_,
      CreateMSIDResult_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CreateMSIDResult, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CreateMSIDResult, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(CreateMSIDResult));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CreateMSIDResult_descriptor_, CreateMSIDResult::default_instance_);
  MessageType_descriptor_ = file->enum_type(0);
  GenericPacket::default_instance_->InitAsDefaultInstance();
  BufferPacketInfo::default_instance_->InitAsDefaultInstance();
  BufferPacketMessage::default_instance_->InitAsDefaultInstance();
  BufferPacket::default_instance_->InitAsDefaultInstance();
  ValidatedBufferPacketMessage::default_instance_->InitAsDefaultInstance();
  ContactInfo::default_instance_->InitAsDefaultInstance();
  ContactNotification::default_instance_->InitAsDefaultInstance();
  InstantFileNotification::default_instance_->InitAsDefaultInstance();
  PrivateShareNotification::default_instance_->InitAsDefaultInstance();
  InstantMessage::default_instance_->InitAsDefaultInstance();
  StoreMessagesResult::default_instance_->InitAsDefaultInstance();
  CreateMSIDResult::default_instance_->InitAsDefaultInstance();
}

void protobuf_BuildDesc_packet_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  pool->InternalBuildGeneratedFile(
    "\n\014packet.proto\022\rpackethandler\"0\n\rGeneric"
    "Packet\022\014\n\004data\030\001 \002(\014\022\021\n\tsignature\030\002 \002(\014\""
    "X\n\020BufferPacketInfo\022\r\n\005owner\030\001 \002(\014\022\026\n\016ow"
    "nerPublicKey\030\002 \002(\014\022\r\n\005users\030\003 \003(\014\022\016\n\006onl"
    "ine\030\004 \001(\005\"\231\001\n\023BufferPacketMessage\022\021\n\tsen"
    "der_id\030\001 \002(\014\022\031\n\021sender_public_key\030\002 \001(\014\022"
    "\022\n\nRSAenc_key\030\003 \002(\014\022\026\n\016AESenc_message\030\004 "
    "\002(\014\022(\n\004type\030\005 \002(\0162\032.packethandler.Messag"
    "eType\"p\n\014BufferPacket\0220\n\nowner_info\030\001 \003("
    "\0132\034.packethandler.GenericPacket\022.\n\010messa"
    "ges\030\002 \003(\0132\034.packethandler.GenericPacket\""
    "x\n\034ValidatedBufferPacketMessage\022\016\n\006sende"
    "r\030\001 \002(\014\022\017\n\007message\030\002 \002(\014\022\r\n\005index\030\003 \002(\014\022"
    "(\n\004type\030\004 \002(\0162\032.packethandler.MessageTyp"
    "e\"\205\001\n\013ContactInfo\022\014\n\004name\030\001 \001(\014\022\020\n\010birth"
    "day\030\002 \001(\014\022\025\n\roffice_number\030\003 \001(\014\022\016\n\006gend"
    "er\030\004 \001(\014\022\017\n\007country\030\005 \001(\005\022\014\n\004city\030\006 \001(\014\022"
    "\020\n\010language\030\007 \001(\005\"R\n\023ContactNotification"
    "\022\016\n\006action\030\001 \002(\005\022+\n\007contact\030\002 \001(\0132\032.pack"
    "ethandler.ContactInfo\"L\n\027InstantFileNoti"
    "fication\022\017\n\007ser_mdm\030\001 \002(\014\022\016\n\006ser_dm\030\002 \002("
    "\014\022\020\n\010filename\030\003 \002(\014\"\226\001\n\030PrivateShareNoti"
    "fication\022\014\n\004name\030\001 \002(\014\022\014\n\004msid\030\002 \002(\014\022\022\n\n"
    "public_key\030\003 \002(\014\022\023\n\013private_key\030\004 \001(\014\022\016\n"
    "\006admins\030\005 \003(\014\022\021\n\treadonlys\030\006 \003(\014\022\022\n\ndir_"
    "db_key\030\007 \002(\014\"\227\002\n\016InstantMessage\022\016\n\006sende"
    "r\030\001 \002(\014\022\017\n\007message\030\002 \002(\014\022\014\n\004date\030\003 \002(\005\022@"
    "\n\024contact_notification\030\004 \001(\0132\".packethan"
    "dler.ContactNotification\022H\n\030instantfile_"
    "notification\030\005 \001(\0132&.packethandler.Insta"
    "ntFileNotification\022J\n\031privateshare_notif"
    "ication\030\006 \001(\0132\'.packethandler.PrivateSha"
    "reNotification\"J\n\023StoreMessagesResult\022\016\n"
    "\006result\030\001 \002(\014\022\023\n\013stored_msgs\030\002 \002(\005\022\016\n\006fa"
    "iled\030\003 \003(\014\"Y\n\020CreateMSIDResult\022\016\n\006result"
    "\030\001 \002(\014\022\014\n\004name\030\002 \001(\014\022\023\n\013private_key\030\003 \001("
    "\014\022\022\n\npublic_key\030\004 \001(\014*F\n\013MessageType\022\024\n\020"
    "ADD_CONTACT_RQST\020\001\022\017\n\013INSTANT_MSG\020\002\022\020\n\014S"
    "TATUS_CHECK\020\003", 1533,
  &protobuf_BuildDesc_packet_2eproto_AssignGlobalDescriptors);
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_packet_2eproto {
  StaticDescriptorInitializer_packet_2eproto() {
    protobuf_BuildDesc_packet_2eproto();
  }
} static_descriptor_initializer_packet_2eproto_;

const ::google::protobuf::EnumDescriptor* MessageType_descriptor() {
  if (MessageType_descriptor_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return MessageType_descriptor_;
}
bool MessageType_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// ===================================================================

const ::std::string GenericPacket::_default_data_;
const ::std::string GenericPacket::_default_signature_;
GenericPacket::GenericPacket()
  : ::google::protobuf::Message(),
    _unknown_fields_(),
    _cached_size_(0),
    data_(const_cast< ::std::string*>(&_default_data_)),
    signature_(const_cast< ::std::string*>(&_default_signature_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void GenericPacket::InitAsDefaultInstance() {}

GenericPacket::GenericPacket(const GenericPacket& from)
  : ::google::protobuf::Message(),
    _unknown_fields_(),
    _cached_size_(0),
    data_(const_cast< ::std::string*>(&_default_data_)),
    signature_(const_cast< ::std::string*>(&_default_signature_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

GenericPacket::~GenericPacket() {
  if (data_ != &_default_data_) {
    delete data_;
  }
  if (signature_ != &_default_signature_) {
    delete signature_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* GenericPacket::descriptor() {
  if (GenericPacket_descriptor_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return GenericPacket_descriptor_;
}

const GenericPacket& GenericPacket::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return *default_instance_;
}

GenericPacket* GenericPacket::default_instance_ = NULL;

GenericPacket* GenericPacket::New() const {
  return new GenericPacket;
}

const ::google::protobuf::Descriptor* GenericPacket::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* GenericPacket::GetReflection() const {
  if (GenericPacket_reflection_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return GenericPacket_reflection_;
}

// ===================================================================

const ::std::string BufferPacketInfo::_default_owner_;
const ::std::string BufferPacketInfo::_default_ownerpublickey_;


BufferPacketInfo::BufferPacketInfo()
  : ::google::protobuf::Message(),
    _unknown_fields_(),
    _cached_size_(0),
    owner_(const_cast< ::std::string*>(&_default_owner_)),
    ownerpublickey_(const_cast< ::std::string*>(&_default_ownerpublickey_)),
    users_(),
    online_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void BufferPacketInfo::InitAsDefaultInstance() {}

BufferPacketInfo::BufferPacketInfo(const BufferPacketInfo& from)
  : ::google::protobuf::Message(),
    _unknown_fields_(),
    _cached_size_(0),
    owner_(const_cast< ::std::string*>(&_default_owner_)),
    ownerpublickey_(const_cast< ::std::string*>(&_default_ownerpublickey_)),
    users_(),
    online_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

BufferPacketInfo::~BufferPacketInfo() {
  if (owner_ != &_default_owner_) {
    delete owner_;
  }
  if (ownerpublickey_ != &_default_ownerpublickey_) {
    delete ownerpublickey_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* BufferPacketInfo::descriptor() {
  if (BufferPacketInfo_descriptor_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return BufferPacketInfo_descriptor_;
}

const BufferPacketInfo& BufferPacketInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return *default_instance_;
}

BufferPacketInfo* BufferPacketInfo::default_instance_ = NULL;

BufferPacketInfo* BufferPacketInfo::New() const {
  return new BufferPacketInfo;
}

const ::google::protobuf::Descriptor* BufferPacketInfo::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* BufferPacketInfo::GetReflection() const {
  if (BufferPacketInfo_reflection_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return BufferPacketInfo_reflection_;
}

// ===================================================================

const ::std::string BufferPacketMessage::_default_sender_id_;
const ::std::string BufferPacketMessage::_default_sender_public_key_;
const ::std::string BufferPacketMessage::_default_rsaenc_key_;
const ::std::string BufferPacketMessage::_default_aesenc_message_;

BufferPacketMessage::BufferPacketMessage()
  : ::google::protobuf::Message(),
    _unknown_fields_(),
    _cached_size_(0),
    sender_id_(const_cast< ::std::string*>(&_default_sender_id_)),
    sender_public_key_(const_cast< ::std::string*>(&_default_sender_public_key_)),
    rsaenc_key_(const_cast< ::std::string*>(&_default_rsaenc_key_)),
    aesenc_message_(const_cast< ::std::string*>(&_default_aesenc_message_)),
    type_(1) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void BufferPacketMessage::InitAsDefaultInstance() {}

BufferPacketMessage::BufferPacketMessage(const BufferPacketMessage& from)
  : ::google::protobuf::Message(),
    _unknown_fields_(),
    _cached_size_(0),
    sender_id_(const_cast< ::std::string*>(&_default_sender_id_)),
    sender_public_key_(const_cast< ::std::string*>(&_default_sender_public_key_)),
    rsaenc_key_(const_cast< ::std::string*>(&_default_rsaenc_key_)),
    aesenc_message_(const_cast< ::std::string*>(&_default_aesenc_message_)),
    type_(1) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

BufferPacketMessage::~BufferPacketMessage() {
  if (sender_id_ != &_default_sender_id_) {
    delete sender_id_;
  }
  if (sender_public_key_ != &_default_sender_public_key_) {
    delete sender_public_key_;
  }
  if (rsaenc_key_ != &_default_rsaenc_key_) {
    delete rsaenc_key_;
  }
  if (aesenc_message_ != &_default_aesenc_message_) {
    delete aesenc_message_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* BufferPacketMessage::descriptor() {
  if (BufferPacketMessage_descriptor_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return BufferPacketMessage_descriptor_;
}

const BufferPacketMessage& BufferPacketMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return *default_instance_;
}

BufferPacketMessage* BufferPacketMessage::default_instance_ = NULL;

BufferPacketMessage* BufferPacketMessage::New() const {
  return new BufferPacketMessage;
}

const ::google::protobuf::Descriptor* BufferPacketMessage::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* BufferPacketMessage::GetReflection() const {
  if (BufferPacketMessage_reflection_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return BufferPacketMessage_reflection_;
}

// ===================================================================



BufferPacket::BufferPacket()
  : ::google::protobuf::Message(),
    _unknown_fields_(),
    _cached_size_(0),
    owner_info_(),
    messages_() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void BufferPacket::InitAsDefaultInstance() {}

BufferPacket::BufferPacket(const BufferPacket& from)
  : ::google::protobuf::Message(),
    _unknown_fields_(),
    _cached_size_(0),
    owner_info_(),
    messages_() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

BufferPacket::~BufferPacket() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* BufferPacket::descriptor() {
  if (BufferPacket_descriptor_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return BufferPacket_descriptor_;
}

const BufferPacket& BufferPacket::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return *default_instance_;
}

BufferPacket* BufferPacket::default_instance_ = NULL;

BufferPacket* BufferPacket::New() const {
  return new BufferPacket;
}

const ::google::protobuf::Descriptor* BufferPacket::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* BufferPacket::GetReflection() const {
  if (BufferPacket_reflection_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return BufferPacket_reflection_;
}

// ===================================================================

const ::std::string ValidatedBufferPacketMessage::_default_sender_;
const ::std::string ValidatedBufferPacketMessage::_default_message_;
const ::std::string ValidatedBufferPacketMessage::_default_index_;

ValidatedBufferPacketMessage::ValidatedBufferPacketMessage()
  : ::google::protobuf::Message(),
    _unknown_fields_(),
    _cached_size_(0),
    sender_(const_cast< ::std::string*>(&_default_sender_)),
    message_(const_cast< ::std::string*>(&_default_message_)),
    index_(const_cast< ::std::string*>(&_default_index_)),
    type_(1) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void ValidatedBufferPacketMessage::InitAsDefaultInstance() {}

ValidatedBufferPacketMessage::ValidatedBufferPacketMessage(const ValidatedBufferPacketMessage& from)
  : ::google::protobuf::Message(),
    _unknown_fields_(),
    _cached_size_(0),
    sender_(const_cast< ::std::string*>(&_default_sender_)),
    message_(const_cast< ::std::string*>(&_default_message_)),
    index_(const_cast< ::std::string*>(&_default_index_)),
    type_(1) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

ValidatedBufferPacketMessage::~ValidatedBufferPacketMessage() {
  if (sender_ != &_default_sender_) {
    delete sender_;
  }
  if (message_ != &_default_message_) {
    delete message_;
  }
  if (index_ != &_default_index_) {
    delete index_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* ValidatedBufferPacketMessage::descriptor() {
  if (ValidatedBufferPacketMessage_descriptor_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return ValidatedBufferPacketMessage_descriptor_;
}

const ValidatedBufferPacketMessage& ValidatedBufferPacketMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return *default_instance_;
}

ValidatedBufferPacketMessage* ValidatedBufferPacketMessage::default_instance_ = NULL;

ValidatedBufferPacketMessage* ValidatedBufferPacketMessage::New() const {
  return new ValidatedBufferPacketMessage;
}

const ::google::protobuf::Descriptor* ValidatedBufferPacketMessage::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* ValidatedBufferPacketMessage::GetReflection() const {
  if (ValidatedBufferPacketMessage_reflection_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return ValidatedBufferPacketMessage_reflection_;
}

// ===================================================================

const ::std::string ContactInfo::_default_name_;
const ::std::string ContactInfo::_default_birthday_;
const ::std::string ContactInfo::_default_office_number_;
const ::std::string ContactInfo::_default_gender_;

const ::std::string ContactInfo::_default_city_;

ContactInfo::ContactInfo()
  : ::google::protobuf::Message(),
    _unknown_fields_(),
    _cached_size_(0),
    name_(const_cast< ::std::string*>(&_default_name_)),
    birthday_(const_cast< ::std::string*>(&_default_birthday_)),
    office_number_(const_cast< ::std::string*>(&_default_office_number_)),
    gender_(const_cast< ::std::string*>(&_default_gender_)),
    country_(0),
    city_(const_cast< ::std::string*>(&_default_city_)),
    language_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void ContactInfo::InitAsDefaultInstance() {}

ContactInfo::ContactInfo(const ContactInfo& from)
  : ::google::protobuf::Message(),
    _unknown_fields_(),
    _cached_size_(0),
    name_(const_cast< ::std::string*>(&_default_name_)),
    birthday_(const_cast< ::std::string*>(&_default_birthday_)),
    office_number_(const_cast< ::std::string*>(&_default_office_number_)),
    gender_(const_cast< ::std::string*>(&_default_gender_)),
    country_(0),
    city_(const_cast< ::std::string*>(&_default_city_)),
    language_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

ContactInfo::~ContactInfo() {
  if (name_ != &_default_name_) {
    delete name_;
  }
  if (birthday_ != &_default_birthday_) {
    delete birthday_;
  }
  if (office_number_ != &_default_office_number_) {
    delete office_number_;
  }
  if (gender_ != &_default_gender_) {
    delete gender_;
  }
  if (city_ != &_default_city_) {
    delete city_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* ContactInfo::descriptor() {
  if (ContactInfo_descriptor_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return ContactInfo_descriptor_;
}

const ContactInfo& ContactInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return *default_instance_;
}

ContactInfo* ContactInfo::default_instance_ = NULL;

ContactInfo* ContactInfo::New() const {
  return new ContactInfo;
}

const ::google::protobuf::Descriptor* ContactInfo::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* ContactInfo::GetReflection() const {
  if (ContactInfo_reflection_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return ContactInfo_reflection_;
}

// ===================================================================



ContactNotification::ContactNotification()
  : ::google::protobuf::Message(),
    _unknown_fields_(),
    _cached_size_(0),
    action_(0),
    contact_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void ContactNotification::InitAsDefaultInstance() {  contact_ = const_cast< ::packethandler::ContactInfo*>(&::packethandler::ContactInfo::default_instance());
}

ContactNotification::ContactNotification(const ContactNotification& from)
  : ::google::protobuf::Message(),
    _unknown_fields_(),
    _cached_size_(0),
    action_(0),
    contact_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

ContactNotification::~ContactNotification() {
  if (this != default_instance_) {
    delete contact_;
  }
}

const ::google::protobuf::Descriptor* ContactNotification::descriptor() {
  if (ContactNotification_descriptor_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return ContactNotification_descriptor_;
}

const ContactNotification& ContactNotification::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return *default_instance_;
}

ContactNotification* ContactNotification::default_instance_ = NULL;

ContactNotification* ContactNotification::New() const {
  return new ContactNotification;
}

const ::google::protobuf::Descriptor* ContactNotification::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* ContactNotification::GetReflection() const {
  if (ContactNotification_reflection_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return ContactNotification_reflection_;
}

// ===================================================================

const ::std::string InstantFileNotification::_default_ser_mdm_;
const ::std::string InstantFileNotification::_default_ser_dm_;
const ::std::string InstantFileNotification::_default_filename_;
InstantFileNotification::InstantFileNotification()
  : ::google::protobuf::Message(),
    _unknown_fields_(),
    _cached_size_(0),
    ser_mdm_(const_cast< ::std::string*>(&_default_ser_mdm_)),
    ser_dm_(const_cast< ::std::string*>(&_default_ser_dm_)),
    filename_(const_cast< ::std::string*>(&_default_filename_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void InstantFileNotification::InitAsDefaultInstance() {}

InstantFileNotification::InstantFileNotification(const InstantFileNotification& from)
  : ::google::protobuf::Message(),
    _unknown_fields_(),
    _cached_size_(0),
    ser_mdm_(const_cast< ::std::string*>(&_default_ser_mdm_)),
    ser_dm_(const_cast< ::std::string*>(&_default_ser_dm_)),
    filename_(const_cast< ::std::string*>(&_default_filename_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

InstantFileNotification::~InstantFileNotification() {
  if (ser_mdm_ != &_default_ser_mdm_) {
    delete ser_mdm_;
  }
  if (ser_dm_ != &_default_ser_dm_) {
    delete ser_dm_;
  }
  if (filename_ != &_default_filename_) {
    delete filename_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* InstantFileNotification::descriptor() {
  if (InstantFileNotification_descriptor_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return InstantFileNotification_descriptor_;
}

const InstantFileNotification& InstantFileNotification::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return *default_instance_;
}

InstantFileNotification* InstantFileNotification::default_instance_ = NULL;

InstantFileNotification* InstantFileNotification::New() const {
  return new InstantFileNotification;
}

const ::google::protobuf::Descriptor* InstantFileNotification::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* InstantFileNotification::GetReflection() const {
  if (InstantFileNotification_reflection_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return InstantFileNotification_reflection_;
}

// ===================================================================

const ::std::string PrivateShareNotification::_default_name_;
const ::std::string PrivateShareNotification::_default_msid_;
const ::std::string PrivateShareNotification::_default_public_key_;
const ::std::string PrivateShareNotification::_default_private_key_;


const ::std::string PrivateShareNotification::_default_dir_db_key_;
PrivateShareNotification::PrivateShareNotification()
  : ::google::protobuf::Message(),
    _unknown_fields_(),
    _cached_size_(0),
    name_(const_cast< ::std::string*>(&_default_name_)),
    msid_(const_cast< ::std::string*>(&_default_msid_)),
    public_key_(const_cast< ::std::string*>(&_default_public_key_)),
    private_key_(const_cast< ::std::string*>(&_default_private_key_)),
    admins_(),
    readonlys_(),
    dir_db_key_(const_cast< ::std::string*>(&_default_dir_db_key_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void PrivateShareNotification::InitAsDefaultInstance() {}

PrivateShareNotification::PrivateShareNotification(const PrivateShareNotification& from)
  : ::google::protobuf::Message(),
    _unknown_fields_(),
    _cached_size_(0),
    name_(const_cast< ::std::string*>(&_default_name_)),
    msid_(const_cast< ::std::string*>(&_default_msid_)),
    public_key_(const_cast< ::std::string*>(&_default_public_key_)),
    private_key_(const_cast< ::std::string*>(&_default_private_key_)),
    admins_(),
    readonlys_(),
    dir_db_key_(const_cast< ::std::string*>(&_default_dir_db_key_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

PrivateShareNotification::~PrivateShareNotification() {
  if (name_ != &_default_name_) {
    delete name_;
  }
  if (msid_ != &_default_msid_) {
    delete msid_;
  }
  if (public_key_ != &_default_public_key_) {
    delete public_key_;
  }
  if (private_key_ != &_default_private_key_) {
    delete private_key_;
  }
  if (dir_db_key_ != &_default_dir_db_key_) {
    delete dir_db_key_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* PrivateShareNotification::descriptor() {
  if (PrivateShareNotification_descriptor_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return PrivateShareNotification_descriptor_;
}

const PrivateShareNotification& PrivateShareNotification::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return *default_instance_;
}

PrivateShareNotification* PrivateShareNotification::default_instance_ = NULL;

PrivateShareNotification* PrivateShareNotification::New() const {
  return new PrivateShareNotification;
}

const ::google::protobuf::Descriptor* PrivateShareNotification::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* PrivateShareNotification::GetReflection() const {
  if (PrivateShareNotification_reflection_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return PrivateShareNotification_reflection_;
}

// ===================================================================

const ::std::string InstantMessage::_default_sender_;
const ::std::string InstantMessage::_default_message_;




InstantMessage::InstantMessage()
  : ::google::protobuf::Message(),
    _unknown_fields_(),
    _cached_size_(0),
    sender_(const_cast< ::std::string*>(&_default_sender_)),
    message_(const_cast< ::std::string*>(&_default_message_)),
    date_(0),
    contact_notification_(NULL),
    instantfile_notification_(NULL),
    privateshare_notification_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void InstantMessage::InitAsDefaultInstance() {  contact_notification_ = const_cast< ::packethandler::ContactNotification*>(&::packethandler::ContactNotification::default_instance());
  instantfile_notification_ = const_cast< ::packethandler::InstantFileNotification*>(&::packethandler::InstantFileNotification::default_instance());
  privateshare_notification_ = const_cast< ::packethandler::PrivateShareNotification*>(&::packethandler::PrivateShareNotification::default_instance());
}

InstantMessage::InstantMessage(const InstantMessage& from)
  : ::google::protobuf::Message(),
    _unknown_fields_(),
    _cached_size_(0),
    sender_(const_cast< ::std::string*>(&_default_sender_)),
    message_(const_cast< ::std::string*>(&_default_message_)),
    date_(0),
    contact_notification_(NULL),
    instantfile_notification_(NULL),
    privateshare_notification_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

InstantMessage::~InstantMessage() {
  if (sender_ != &_default_sender_) {
    delete sender_;
  }
  if (message_ != &_default_message_) {
    delete message_;
  }
  if (this != default_instance_) {
    delete contact_notification_;
    delete instantfile_notification_;
    delete privateshare_notification_;
  }
}

const ::google::protobuf::Descriptor* InstantMessage::descriptor() {
  if (InstantMessage_descriptor_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return InstantMessage_descriptor_;
}

const InstantMessage& InstantMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return *default_instance_;
}

InstantMessage* InstantMessage::default_instance_ = NULL;

InstantMessage* InstantMessage::New() const {
  return new InstantMessage;
}

const ::google::protobuf::Descriptor* InstantMessage::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* InstantMessage::GetReflection() const {
  if (InstantMessage_reflection_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return InstantMessage_reflection_;
}

// ===================================================================

const ::std::string StoreMessagesResult::_default_result_;


StoreMessagesResult::StoreMessagesResult()
  : ::google::protobuf::Message(),
    _unknown_fields_(),
    _cached_size_(0),
    result_(const_cast< ::std::string*>(&_default_result_)),
    stored_msgs_(0),
    failed_() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void StoreMessagesResult::InitAsDefaultInstance() {}

StoreMessagesResult::StoreMessagesResult(const StoreMessagesResult& from)
  : ::google::protobuf::Message(),
    _unknown_fields_(),
    _cached_size_(0),
    result_(const_cast< ::std::string*>(&_default_result_)),
    stored_msgs_(0),
    failed_() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

StoreMessagesResult::~StoreMessagesResult() {
  if (result_ != &_default_result_) {
    delete result_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* StoreMessagesResult::descriptor() {
  if (StoreMessagesResult_descriptor_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return StoreMessagesResult_descriptor_;
}

const StoreMessagesResult& StoreMessagesResult::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return *default_instance_;
}

StoreMessagesResult* StoreMessagesResult::default_instance_ = NULL;

StoreMessagesResult* StoreMessagesResult::New() const {
  return new StoreMessagesResult;
}

const ::google::protobuf::Descriptor* StoreMessagesResult::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* StoreMessagesResult::GetReflection() const {
  if (StoreMessagesResult_reflection_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return StoreMessagesResult_reflection_;
}

// ===================================================================

const ::std::string CreateMSIDResult::_default_result_;
const ::std::string CreateMSIDResult::_default_name_;
const ::std::string CreateMSIDResult::_default_private_key_;
const ::std::string CreateMSIDResult::_default_public_key_;
CreateMSIDResult::CreateMSIDResult()
  : ::google::protobuf::Message(),
    _unknown_fields_(),
    _cached_size_(0),
    result_(const_cast< ::std::string*>(&_default_result_)),
    name_(const_cast< ::std::string*>(&_default_name_)),
    private_key_(const_cast< ::std::string*>(&_default_private_key_)),
    public_key_(const_cast< ::std::string*>(&_default_public_key_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void CreateMSIDResult::InitAsDefaultInstance() {}

CreateMSIDResult::CreateMSIDResult(const CreateMSIDResult& from)
  : ::google::protobuf::Message(),
    _unknown_fields_(),
    _cached_size_(0),
    result_(const_cast< ::std::string*>(&_default_result_)),
    name_(const_cast< ::std::string*>(&_default_name_)),
    private_key_(const_cast< ::std::string*>(&_default_private_key_)),
    public_key_(const_cast< ::std::string*>(&_default_public_key_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

CreateMSIDResult::~CreateMSIDResult() {
  if (result_ != &_default_result_) {
    delete result_;
  }
  if (name_ != &_default_name_) {
    delete name_;
  }
  if (private_key_ != &_default_private_key_) {
    delete private_key_;
  }
  if (public_key_ != &_default_public_key_) {
    delete public_key_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* CreateMSIDResult::descriptor() {
  if (CreateMSIDResult_descriptor_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return CreateMSIDResult_descriptor_;
}

const CreateMSIDResult& CreateMSIDResult::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return *default_instance_;
}

CreateMSIDResult* CreateMSIDResult::default_instance_ = NULL;

CreateMSIDResult* CreateMSIDResult::New() const {
  return new CreateMSIDResult;
}

const ::google::protobuf::Descriptor* CreateMSIDResult::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* CreateMSIDResult::GetReflection() const {
  if (CreateMSIDResult_reflection_ == NULL) protobuf_BuildDesc_packet_2eproto();
  return CreateMSIDResult_reflection_;
}

}  // namespace packethandler
